# This is a basic workflow to help you get started with Actions

name: Heroku Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # include the heroku deployment thing
      - name: Zero-waste Heroku Deploy
        # You may pin to the exact commit or the version.
        # uses: formsort/action-heroku-deploy@282d27ca08cd38ed90e07736f5d6aab2db7dacd6
        uses: formsort/action-heroku-deploy@v1
        with:
          # GitHub repo name with owner (eg. formsort/formsort)
          github_repo: LeftistTachyon/Programming-Simplified-API
          # GITHUB_TOKEN
          github_token: ${{ github.token }}
          # API Key for the Heroku account that will perform the deploy
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # Name of the Heroku app to be deployed
          heroku_app_name: programming-simplified-api
          # The new version of the app to be deployed. Will fall back to `inputs.ref` if not provided.
          # heroku_app_version: # optional
          # Git ref to deploy to Heroku
          ref: master
